version: '3'
services:
  python:
    build: 
      context: .
      dockerfile: app/Dockerfile
    container_name: pythona7
    restart: always
    depends_on:
      - db
    links:
      - db
    env_file: .env    
    environment:
       DB_PORT: 3306
       DB_HOST: db
       DB_DATABASE: restaurant
       DB_USERNAME: ${DB_USERNAME}
       DB_PASSWORD: ${DB_PASSWORD}
       SECRET_KEY: ${SECRET_KEY}
       WTF_CSRF_SECRET_KEY: ${WTF_CSRF_SECRET_KEY}       
       HOST: "0.0.0.0"
       PORT: 8080
    volumes:
      - ./logapi/:/app/logs
    networks:
      - grupoa7

  db:
    image: mariadb:10.3
    container_name: dba7
    restart: always
    environment:
      MYSQL_DATABASE: restaurant
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - dba7:/var/lib/mysql
      - ./APIRest/database/restaurant.sql:/docker-entrypoint-initdb.d/restaurant.sql:ro
    secrets:
      - db_root_password
    networks:
      - grupoa7


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin7
    restart: always
    ports:
      - 7007:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
    links:
      - db
    depends_on:
      - db
    networks:
      - grupoa7


  apache-waf:
    build: ./apache #./waf/ en un futuro
    container_name: apachea7
    ports:
      - 443:443
      - 6007:80
    depends_on:
      - python
    links:
      - python
    volumes:
      - ./WebClient:/var/www/html # en el futuro se quita
      - ./logwaf:/var/log/apache2
    networks:
      - grupoa7


secrets:
  db_root_user:
    file: ./secrets/db._rootusr.txt
  db_root_password:
    file: ./secrets/db_rootpwd.txt
  db_user_username:
    file: ./secrets/db_userusr.txt
  db_user_password:
    file: ./secrets/db_userpwd.txt

volumes:
  dba7:    

networks:
  grupoa7: